// export const REST_API_END_POINT = "http://localhost:4000/webservice/";
export const REST_API_END_POINT = 'http://localhost:4000/webservice/'

export const JWT_SECRET = '3f34d7hjjjdgt876'

export const permissons = [
  { id: 1, action: 'Add School' },
  { id: 2, action: 'Edit School' },
  { id: 3, action: 'Set School Status' },
  { id: 4, action: 'Delete School' },
  { id: 5, action: 'Add Department' },
  { id: 6, action: 'Edit Department' },
  { id: 7, action: 'Set Department Status' },
  { id: 8, action: 'Delete Department' },
  { id: 9, action: 'Add Subjects' },
  { id: 10, action: 'View Subjects' },
  { id: 11, action: 'Delete Subjects' },
  { id: 12, action: 'Add HODs' },
  { id: 13, action: 'View HOD Profile' },
  { id: 14, action: 'Edit HOD Credentials' },
  { id: 15, action: 'Deactivate HOD' },
  { id: 16, action: 'Delete HOD' },
  { id: 17, action: 'Add Teacher' },
  { id: 18, action: 'View Teacher Profile' },
  { id: 19, action: 'Edit Teacher Credentials' },
  { id: 20, action: 'Deactivate Teacher' },
  { id: 21, action: 'Delete Teacher' },
  { id: 22, action: 'Add Department Analytics' },
  { id: 23, action: 'View Department Analytics' },
  { id: 24, action: 'Add Subject Analytics' },
  { id: 25, action: 'View Subject Analytics' },
  { id: 26, action: 'View Grade' },
  { id: 27, action: 'Add Grade' },
  { id: 28, action: 'Edit Grade' },
  { id: 29, action: 'Delete Grade' },
  { id: 30, action: 'View Class' },
  { id: 31, action: 'Add Class' },
  { id: 32, action: 'Edit Class' },
  { id: 33, action: 'Delete Class' },
  { id: 34, action: 'View Test' },
  { id: 35, action: 'Add Test' },
  { id: 36, action: 'Edit Test' },
  { id: 37, action: 'Delete Test' },
  { id: 38, action: 'Add Marksheet' },
]
